[2023-06-14T02:14:57.103+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:14:57.119+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:14:57.120+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-06-14T02:14:57.147+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresFileOperator): llenar_tabla_from_file> on 2023-06-14 02:13:35.804016+00:00
[2023-06-14T02:14:57.154+0000] {standard_task_runner.py:57} INFO - Started process 116 to run task
[2023-06-14T02:14:57.157+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vamosSigue', 'llenar_tabla_from_file', 'manual__2023-06-14T02:13:35.804016+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dbeaverFunciona.py', '--cfg-path', '/tmp/tmpmx9lkfoi']
[2023-06-14T02:14:57.158+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask llenar_tabla_from_file
[2023-06-14T02:14:57.225+0000] {task_command.py:410} INFO - Running <TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [running]> on host a26553e1bb12
[2023-06-14T02:14:57.367+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vamosSigue' AIRFLOW_CTX_TASK_ID='llenar_tabla_from_file' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T02:13:35.804016+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T02:13:35.804016+00:00'
[2023-06-14T02:14:57.369+0000] {postgres.py:158} INFO - Running copy expert: COPY datos FROM STDIN, filename: /opt/***/dags/filese.tsv
[2023-06-14T02:14:57.386+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T02:14:57.441+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vamosSigue, task_id=llenar_tabla_from_file, execution_date=20230614T021335, start_date=20230614T021457, end_date=20230614T021457
[2023-06-14T02:14:57.491+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T02:14:57.517+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
