[2023-06-14T02:30:08.323+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:30:08.341+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:30:08.342+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2023-06-14T02:30:08.370+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresFileOperator): llenar_tabla_from_file> on 2023-06-14 02:13:35.804016+00:00
[2023-06-14T02:30:08.377+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2023-06-14T02:30:08.381+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vamosSigue', 'llenar_tabla_from_file', 'manual__2023-06-14T02:13:35.804016+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dbeaverFunciona.py', '--cfg-path', '/tmp/tmpl8rczsqt']
[2023-06-14T02:30:08.382+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask llenar_tabla_from_file
[2023-06-14T02:30:08.462+0000] {task_command.py:410} INFO - Running <TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [running]> on host b41452b45446
[2023-06-14T02:30:08.626+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vamosSigue' AIRFLOW_CTX_TASK_ID='llenar_tabla_from_file' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T02:13:35.804016+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T02:13:35.804016+00:00'
[2023-06-14T02:30:08.628+0000] {postgres.py:158} INFO - Running copy expert: COPY datos FROM STDIN, filename: /opt/***/dags/filese.tsv
[2023-06-14T02:30:08.644+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T02:30:08.697+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vamosSigue, task_id=llenar_tabla_from_file, execution_date=20230614T021335, start_date=20230614T023008, end_date=20230614T023008
[2023-06-14T02:30:08.753+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T02:30:08.780+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
